name: GitHub Actions Demo
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v**
  workflow_call:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Install NVM
        working-directory: progetto-frontend-vanilla
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm --version
          nvm install
          nvm use
      - name: Build
        working-directory: progetto-frontend-vanilla
        run: |
          npm install
          npm run build
      - name: Chromatic design-system-react
        working-directory: design-system/react
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          npm install
          npx -yes chromatic --force-rebuild
      - name: Build storybook-static
        working-directory: design-system/react
        run: |
          npm run build-storybook
          cp -R storybook-static ../../progetto-frontend-vanilla/dist/storybook-static
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}-${{ github.sha }}
          path: ./progetto-frontend-vanilla/dist/
      - name: Build design system
        working-directory: design-system/react
        run: |
          npm run build
          npm run build-umd
      - name: Upload the design system artifact
        uses: actions/upload-artifact@v2
        with:
          name: design-system-${{github.ref_name}}-${{ github.sha }}
          path: ./design-system/react/dist/
      
